project:
  type: website
  output-dir: docs
  resources:
    - CNAME
    - robots.txt
    - assets/**

website:
  title: "My personal professional website"
  description: "This is a professional personal page, I speak of R programming, scientific development, web development, reproducibility and photography."
  site-url: https://albansagouis.com
  open-graph: true
  twitter-card: true
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: "About me"
      - href: cv.qmd
      - href: blog.qmd
    tools:
      - icon: github
        menu:
          - text: Website source
            href: https://github.com/AlbanSagouis/albansagouis.github.io
          - text: My repositories
            href: https://github.com/AlbanSagouis/
  page-footer:
    center: "© 2024–2026 Alban Sagouis · Built with [Quarto](https://quarto.org)"

date-format: 'DD/MM/YYYY'
format:
  html:
    theme:
      light: lux
      dark: darkly
    css: styles.css
    toc: true
    lang: en-gb
    smooth-scroll: true
    link-external-icon: true
    link-external-newwindow: true
    include-in-header: _includes/academicons.html

editor: source
